spring.profiles.include=oauth
spring.jpa.show-sql=true
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.h2.console.enabled=true
# Server Response HTTP UTF-8 설정
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# Mustache 템플릿 인코딩 설정
spring.mustache.servlet.charset=UTF-8
# Mustache 템플릿 파일 변경 시 즉시 반영 (개발용 캐시 비활성화)
spring.mustache.cache=false

# SQL 가독성을 위해 정렬(포맷팅)해서 출력
spring.jpa.properties.hibernate.format_sql=true

# SQL에 들어가는 파라미터 값(? 표시)을 실제 값으로 출력
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

spring.session.store-type=jdbc